<?php
 return [
  'name' => 'componentsPageHeader',
  'label' => 'Components - Page Header',
  'info' => '',
  'type' => 'singleton',
  'fields' => [
    0 => [
      'name' => 'filterBarGrantStatus',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    1 => [
      'name' => 'filterBarPartnerTypes',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    2 => [
      'name' => 'filterBarReplenishmentPeriods',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    3 => [
      'name' => 'filterBarLocations',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    4 => [
      'name' => 'filterBarComponents',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'filterBarPartnerTypes',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    6 => [
      'name' => 'fiilterBarGrantStatus',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'filterBarReplenishmentPeriods',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    8 => [
      'name' => 'filterBarDonors',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    9 => [
      'name' => 'tabOverview',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    10 => [
      'name' => 'tabSigned',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    11 => [
      'name' => 'tabCommitment',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    12 => [
      'name' => 'tabDisbursement',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    13 => [
      'name' => 'tabBudgets',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    14 => [
      'name' => 'tabAllocation',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    15 => [
      'name' => 'tabEligibility',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    16 => [
      'name' => 'tabDocuments',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    17 => [
      'name' => 'tabGrants',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    18 => [
      'name' => 'tabResults',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    19 => [
      'name' => 'tabPerformanceRating',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    20 => [
      'name' => 'tabPerformanceFramework',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    21 => [
      'name' => 'mobileFilterBar',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    22 => [
      'name' => 'results',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => '',
  'meta' => NULL,
  '_created' => 1701788608,
  '_modified' => 1701788608,
  'color' => NULL,
  'revisions' => false,
];