<?php
 return [
  'name' => 'componentsChartsEligibility',
  'label' => 'Components - Charts - Eligibility',
  'info' => '',
  'type' => 'singleton',
  'fields' => [
    0 => [
      'name' => 'statusEligible',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    1 => [
      'name' => 'statusNotEligible',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    2 => [
      'name' => 'statusTransitionFunding',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    3 => [
      'name' => 'eligibility',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    4 => [
      'name' => 'year',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'countryName',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    6 => [
      'name' => 'hiv',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'malaria',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    8 => [
      'name' => 'tuberculosis',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    9 => [
      'name' => 'diseaseBurdenExtreme',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    10 => [
      'name' => 'diseaseBurdenSevere',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    11 => [
      'name' => 'diseaseBurdenHigh',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    12 => [
      'name' => 'diseaseBurdenNotHigh',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    13 => [
      'name' => 'diseaseBurdenModerate',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    14 => [
      'name' => 'diseaseBurdenLow',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    15 => [
      'name' => 'diseaseBurdenNone',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    16 => [
      'name' => 'incomeLevelsNone',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    17 => [
      'name' => 'incomeLevelsLow',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    18 => [
      'name' => 'incomeLevelsLowerLower',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    19 => [
      'name' => 'incomeLevelsLowerMiddle',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    20 => [
      'name' => 'incomeLevelsUpperLower',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    21 => [
      'name' => 'incomeLevelsUpperMiddle',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    22 => [
      'name' => 'incomeLevelsHigh',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    23 => [
      'name' => 'scatterplotEligibility',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    24 => [
      'name' => 'scatterplotDiseaseBurden',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    25 => [
      'name' => 'scatterplotIncomeLevel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    26 => [
      'name' => 'incomeLevel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    27 => [
      'name' => 'diseaseBurden',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    28 => [
      'name' => 'aggregateBy',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => '',
  'meta' => NULL,
  '_created' => 1701788608,
  '_modified' => 1701788608,
  'color' => NULL,
  'revisions' => false,
];