<?php
 return [
  'name' => 'componentsChartsBudgets',
  'label' => 'Components - Charts - Budgets',
  'info' => '',
  'type' => 'singleton',
  'fields' => [
    0 => [
      'name' => 'totalAmount',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    1 => [
      'name' => 'budget',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    2 => [
      'name' => 'flowLandscapeLevel1',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    3 => [
      'name' => 'flowLandscapeLevel2',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    4 => [
      'name' => 'flowCostCategory',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'flowTooltipComponent',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    6 => [
      'name' => 'flowTooltipDrilldown',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'timeCycleTooltipBudgets',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    8 => [
      'name' => 'treemapTooltipDefaultKeyLabel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    9 => [
      'name' => 'treemapTooltipGrant',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    10 => [
      'name' => 'geomapLabelBudgets',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    11 => [
      'name' => 'notAvailable',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    12 => [
      'name' => 'geomapDefaultValue',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    13 => [
      'name' => 'treemapTooltipAllocation',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    14 => [
      'name' => 'amount',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => '',
  'meta' => NULL,
  '_created' => 1644506920,
  '_modified' => 1683991328,
  'color' => NULL,
  'revisions' => false,
];
