<?php
 return [
  'name' => 'modulesCountryDetail',
  'label' => 'Modules - Country Detail',
  'info' => '',
  'type' => 'singleton',
  'fields' => [
    0 => [
      'name' => 'seeResultsStart',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    1 => [
      'name' => 'seeResultsEnd',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    2 => [
      'name' => 'investments',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    3 => [
      'name' => 'disbursed',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    4 => [
      'name' => 'committed',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'signed',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    6 => [
      'name' => 'fundManager',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'radialVizDescription',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    8 => [
      'name' => 'mechanismContactsLabel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    9 => [
      'name' => 'PrincipalRecipientsLabel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    10 => [
      'name' => 'countryOverviewTitle',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    11 => [
      'name' => 'prevPrincipalRecipientLabel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    12 => [
      'name' => 'currPrincipalRecipientLabel',
      'type' => 'text',
      'label' => '',
      'info' => '',
      'group' => '',
      'i18n' => true,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => '',
  'meta' => NULL,
  '_created' => 1701788608,
  '_modified' => 1701788608,
  'color' => NULL,
  'revisions' => false,
];